example = "Python"
print (example [0])
example = "Python"
print (example [-1])
example = "Python"
print (example [-3:])
example = "Python"
print (example [::-1])
example = "Python"
print (example [1:6:2])
